print('olá, mundo!')
print('estou com fome!')
print("gostaria de estar dormindo")
print("queria estar na praia")
print('quero viajar')
print('estou dura e lisa')
print('estou devendo')
print('eu amo meu namorado')
print('que não é meu namorado')
print('meu aniversário está chegando!')